spring:
  #邮箱配置
  mail:
    host: smtp.163.com
    username: 
    #QQ邮箱的授权码
    password: 
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
recevier: 